version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        ENV_FILE: .docker/.env.${ENV:-test}
    image: isanore-store:latest
    container_name: isanore-store
    ports:
      - "9000:9000"
    env_file:
      - .docker/.env.${ENV:-test}